### PR TITLE
Doc cleanup in prep for manuscript and repo cleanup/polish

### PR DESCRIPTION
**Pull request by JamesColl-NOAA**
Cleans up docs and adds polish in prep for manuscript related to [#66](https://github.com/NOAA-OWP/hydrofabric/issues/66).  See readme and vignettes for raw text, HTML should render once merged in.

### CODE REVIEW

**Comment by JamesColl-NOAA** [comment]
In your review, I'm really looking for the following pieces:

- [ ] Vignette text review as the pre-manuscript intro and methods
- [ ] Throw that reference database crosswalk url in a comment on [this function](https://github.com/NOAA-OWP/RRASSLER/blob/docs/R/crosswalk_hull_to_hydrofabric_value.R).

**Comment by mikejohnson51** [comment]
Lets refine this with the internal and peer review of the corresponding paper! Marking as done for now

**Review by JamesColl-NOAA — COMMENTED** [review]
Pushing this through to reflect the data model, state of documentation, and improve install as a package.  We'll add backlog tasks to reflect the changes needed for further refinement and improved hydrofabric utilities.

**Review by mikejohnson51 — COMMENTED** [review]
Lets call this good for now pre-RRASLER paper

**Review by mikejohnson51 — APPROVED** [review]

**Pull request merged**
